In [8]:
import pandas as pd
import numpy as np

Reading dataframe

In [10]:
df =  pd.read_csv(r"C:\Users\UAE LAPTOP BAZAR\Downloads\customer (1).csv")
df.head(6)

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No
5   31  Female  Average    School       Yes

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,2:4],df.iloc[:,-1],test_size=0.2)
X_train.head(5)

review education
24  Average        PG
37  Average        PG
19     Poor        PG
27     Poor        PG
12     Poor    School

In [43]:
X_test.head(5)  

review education
1      Poor        UG
10     Good        UG
18     Good    School
14     Poor        PG
8   Average        UG

In [44]:
y_train.head(5) 

24    Yes
37    Yes
19    Yes
27     No
12     No
Name: purchased, dtype: object

In [42]:
y_test.head(5)

1      No
10    Yes
18     No
14    Yes
8      No
Name: purchased, dtype: object

In [51]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [52]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [70]:
y_test

1      No
10    Yes
18     No
14    Yes
8      No
47    Yes
25     No
23     No
16    Yes
7     Yes
Name: purchased, dtype: object

In [45]:
from sklearn.preprocessing import OrdinalEncoder


In [53]:
enc = OrdinalEncoder(categories=[['Average', 'Poor', 'Good'],['School', 'UG', 'PG']])
enc.fit(X_train)


OrdinalEncoder(categories=[['Average', 'Poor', 'Good'], ['School', 'UG', 'PG']])

In [55]:
X_train= enc.transform(X_train)
X_test = enc.transform(X_test)

In [ ]:
X_train

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [85]:
le.fit(y_train)

LabelEncoder()

In [86]:
le.classes_

array([0, 1])

In [77]:
y_train= le.transform(y_train)   

In [79]:
y_train

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0])

In [74]:
y_test


1      No
10    Yes
18     No
14    Yes
8      No
47    Yes
25     No
23     No
16    Yes
7     Yes
Name: purchased, dtype: object

In [81]:
y_test = le.fit_transform(y_test)       

In [82]:
y_test

array([0, 1, 0, 1, 0, 1, 0, 0, 1, 1])

In [94]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [95]:
svc_model = SVC(kernel='linear')
svc_model.fit(X_train, y_train)

SVC(kernel='linear')

In [97]:
y_pred = svc_model.predict(X_test)

In [98]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8
